/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "no-dep-cpp-lib.h"
#include <cassert>

int main() {
    no_dep_cpp_lib::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    return 0;
}
