/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef NO_DEP_CPP_LIB_H
#define NO_DEP_CPP_LIB_H

#ifdef _WIN32
#define NO_DEP_CPP_LIB_EXPORT_FUNC __declspec(dllexport)
#else
#define NO_DEP_CPP_LIB_EXPORT_FUNC
#endif

#include <string>

namespace no_dep_cpp_lib {
    class Greeter {
        public:
        std::string NO_DEP_CPP_LIB_EXPORT_FUNC greeting();
    };
}

#endif
